### ISSUE TITLE
Error after upgrading to Angular 5

### ISSUE THREAD

**Issue by hkjeffchan** [kreuzerk/primeNG-advanced-growl#107] opened 2017-11-09 09:43 UTC
@angular/cli@1.5.0
@angular/common@5.0.1
@angular/compiler@5.0.1
@angular/compiler-cli@5.0.1
typescript@2.4.2
rxjs@5.5.2

ERROR in node_modules/primeng-advanced-growl/lib/messages/adv-growl.hoverHelper.ts(37,16): error TS2684: The 'this' context of type 'Observable<{}>' is not assignable to method's 'this' of type 'Observable<Notification<{}>>'.
  Type '{}' is not assignable to type 'Notification<{}>'.
    Property 'kind' is missing in type '{}'.

**Comment by kreuzerk** [comment] 2017-11-10 17:09
Hy @hkjeffchan I have found the solution. Your PR was already quiet near. The problem is that we should not use Observable.empty() inside switchMap. Because Observable.empty() completes immediately. With the use of materialize() and dematerialize() this lets all messages dissapear. I have changed the code to now use never which is the correct operator for this case. I will try to release this Bugfix with 2.5.1 this weekend. Notice that I have not officially testet the lib with angular 5. This is still on my todo list. But in my opinion the library should also work with angular 5 after this fix.

**Comment by kreuzerk** [comment] 2017-11-11 12:46
This issue should be fixed with 2.5.1 - Therefore I am going to close this issue

**Closed by kreuzerk** 2017-11-11 12:46 UTC

**Comment by kreuzerk** [comment] 2017-11-13 11:57
At the moment we are just delivering pure ts files. This was the easiest way at the beginning but now seems to be a problem. I think we need to rethink how we package the library for Angular 5.

**Comment by kreuzerk** [comment] 2017-11-14 07:12
I am currently working on a Angular 5 compatible version. I have to change some things. Especially how the module is packaged. I will let you know when it is ready.

**Comment by kreuzerk** [comment] 2017-11-15 07:04
@hkjeffchan I have released the first angular 5 compatible version. Notice this is a prerelease version. Can you try if this version works for you. It will also good if we move the discussion about angular 5 into this issue. https://github.com/kreuzerk/primeNG-advanced-growl/issues/116. Looking forward to hear from you
